### PR TITLE
rid for tracing reconciliation log output

### PR DESCRIPTION
**Pull request by maknop**
The purpose of this PR is to add a reconciliation id to the ENO logs like Clowder has. 
image

### CODE REVIEW

**Review by psav — DISMISSED** [review]
Question here about ctx

**Review by adamrdrew — APPROVED** [review]
LGTM. Most of the change surface area here is actually changing the way you log, not the contents of the logs themselves. The change to add rid to the logs like clowder is actually like a line or two. In a perfect world you'd do these in separate PRs, but let's be real I do stuff like this all the time. So, LGTM!

**Comment by adamrdrew** [comment]
I deleted a comment from @psav only to try and get merging unblocked. @maknop already addressed the feedback, I don't know what GH is mad about.

**Review by adamrdrew — APPROVED** [review]
Why is github fighting me?

**Pull request merged**
