### PR TITLE
Udpate frontend-operator and enable GenerateNavJSON for eph envs

### PR DESCRIPTION
**Pull request by adamrdrew**
This PR updates the frontend-operator and brings in the new GenerateChromeConfig option. This will ensure that chrome configs are built on the fly for apps launched in ephemeral environments.

### CODE REVIEW

**Comment by adamrdrew** [comment]
I'm going to need to leave this out so I can use the system in its current state for testing, as we've found a problem with how chrome picks up the sso url. I'll circle back to this as soon as I can.

**Comment by maknop** [comment]
Let me know and I'll review it :D

**Review by maknop — COMMENTED** [review]
Looks good to me :smile: PR check failing is not relevant to requested code changes.

**Review by maknop — APPROVED** [review]

**Pull request merged**
